name: Localazy Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  localazy-upload:
    name: Upload source keys to Localazy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload to Localazy
        uses: localazy/upload@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
